apps/publication/urls.py
from django.urls import path
from .views import (
    index,
    TopicListView,
    RedactorListView,
    RedactorDetailView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperUpdateView,
    NewspaperCreateView,
    NewspaperDeleteView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("topics/", TopicListView.as_view(), name="topic-list"),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path("topics/<int:pk>/update/", TopicUpdateView.as_view(), name="topic-update"),
    path("topics/<int:pk>/delete/", TopicDeleteView.as_view(), name="topic-delete"),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/<int:pk>", RedactorDetailView.as_view(), name="redactor-detail"),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path("newspapers/<int:pk>", NewspaperDetailView.as_view(), name="newspaper-detail"),
    path("newspapers/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path("newspapers/<int:pk>/update/", NewspaperUpdateView.as_view(), name="newspaper-update"),
    path("newspapers/<int:pk>/delete/", NewspaperDeleteView.as_view(), name="newspaper-delete"),
]

app_name = "home"

publication_tracking_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("apps.authentication.urls")),
    path("", include("apps.publication.urls")),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer-auth.html
<footer class="footer position-absolute bottom-2 py-2 w-100">
      <div class="container">
        <div class="row align-items-center justify-content-lg-between">
          <div class="col-8 mx-auto text-center mt-1">
           <p class="mb-0 copyright text-center text-white">
              &copy; Coded by <a href="https://www.linkedin.com/in/olena-bukhova-525543360/" class="font-weight-bold text-white" target="_blank">Olena Bukhova</a>.
          </p>
          </div>
        </div>
      </div>
    </footer>

templates/includes/footer.html
  <!-- -------- START FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->
  <footer class="footer py-5">
    <div class="container">
      <div class="row">
        <div class="col-8 mx-auto text-center mt-1">
          <p class="mb-0 text-secondary">
              &copy; Coded by <a href="https://www.linkedin.com/in/olena-bukhova-525543360/" class="font-weight-bold" target="_blank">Olena Bukhova</a>.
          </p>
        </div>
      </div>
    </div>
  </footer>
  <!-- -------- END FOOTER 3 w/ COMPANY DESCRIPTION WITH LINKS & SOCIAL ICONS & COPYRIGHT ------- -->

templates/includes/navigation-transparent.html
  <!-- Navbar Transparent -->
  <nav class="navbar navbar-expand-lg position-absolute top-0 z-index-3 w-100 shadow-none my-3  navbar-transparent ">
    <div class="container">
      <a class="navbar-brand font-weight-bolder ms-sm-3" href="{% url 'home:index' %}" rel="tooltip" data-placement="bottom">
        <img src="{{ ASSETS_ROOT }}/assets/img/logo-ct-light.png" class="footer-logo" alt="main_logo">
      </a>
    <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0 ms-lg-12 ps-lg-5" id="navigation">
        <ul class="navbar-nav navbar-nav-hover ms-auto">
          {% if request.user.is_authenticated %}
            <li class="nav-item ms-lg-auto">
              <a class="nav-link nav-link-icon me-2" 
                href="{% url 'logout' %}">
                <i class="fa fa-sign-out me-1"></i>
                <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign OUT">Logout</p>
              </a>
            </li>          
          {% endif %}
        </ul>
    </div>
    </div>
  </nav>
  <!-- End Navbar -->

templates/includes/navigation.html
  <!-- Navbar -->
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">

        <nav class="navbar navbar-expand-lg  blur border-radius-xl top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid px-0">
            <a class="navbar-brand font-weight-bolder ms-sm-3" href="{% url 'home:index' %}" rel="tooltip" data-placement="bottom">
              <img src="{{ ASSETS_ROOT }}/assets/img/logo-ct-dark.png" class="footer-logo" alt="main_logo">
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>

            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-auto">
                <li class="nav-item mx-3">
                  <a href="{% url 'home:newspaper-list' %}" class="nav-link ps-2 d-flex cursor-pointer align-items-center text-md">
                    <i class="material-icons opacity-6 me-2 text-md">newspaper</i>
                    Newspapers
                  </a>
                </li>
                <li class="nav-item mx-3">
                  <a href="{% url 'home:redactor-list' %}" class="nav-link ps-2 d-flex cursor-pointer align-items-center text-md">
                    <i class="material-icons opacity-6 me-2 text-lg">groups_2</i>
                    Redactors
                  </a>
                </li>

                <!-- For desktop versions -->
                <li class="nav-item dropdown dropdown-hover mx-3 ms-lg-auto my-auto d-none d-lg-block">
                  <a class="nav-link nav-link-icon ps-2 d-flex cursor-pointer align-items-center me-2">
                    <img src="{{ ASSETS_ROOT }}/assets/img/profile-icon.svg" alt="profile-icon" class="icon icon-outline icon-xs ms-auto ms-md-2">
                  </a>

                  <div class="dropdown-menu dropdown-menu-end dropdown-menu-animation dropdown-md dropdown-md-responsive p-3 border-radius-xl mt-0 mt-lg-3" aria-labelledby="dropdownMenuBlocks">
                      <div class="d-none d-lg-block">
                        <ul class="list-group">
                        {% if request.user.is_authenticated %}
                          <li class="nav-item list-group-item border-0 p-0 dropdown dropdown-hover dropdown-subitem">
                          <a href="{{ user.get_absolute_url }}" class="dropdown-item border-radius-md px-4 py-2">
                          <span>My profile</span>
                          </a>
                          </li>

                          <li class="nav-item list-group-item border-0 p-0 dropdown dropdown-hover dropdown-subitem">
                            <form method="post" action="{% url 'logout' %}">
                              {% csrf_token %}
                              <button type="submit" class="btn btn-sm bg-gradient-primary mb-0 me-1 mt-2 mt-md-0 dropdown-item border-radius-md px-4 py-2" >
                                Logout
                              </button>
                            </form>
                          </li>
                        {% else %}
                          <li class="nav-item list-group-item border-0 p-0 dropdown dropdown-hover dropdown-subitem">
                            <a href="{% url 'login' %}" class="dropdown-item border-radius-md px-4 py-2">
                            <span>My profile</span>
                            </a>
                          </li>

                          <li class="nav-item list-group-item border-0 p-0 dropdown dropdown-hover dropdown-subitem">
                            <a href="{% url 'login' %}" class="btn btn-sm bg-gradient-primary mb-0 me-1 mt-2 mt-md-0 dropdown-item border-radius-md px-4 py-2">
                              <span>Login</span>
                            </a>
                          </li>
                        {% endif %}
                        </ul>
                      </div>
                  </div>
                </li>

                <!-- For mobile versions -->
                <li class="nav-item ms-lg-auto d-block d-lg-none mx-3 dropdown dropdown-hover dropdown-subitem">
                  {% if request.user.is_authenticated %}
                    <a href="{{ user.get_absolute_url }}" class="nav-link d-flex align-items-center text-md ps-2 dropdown-item border-radius-md">
                    <i class="material-icons opacity-6 me-2 text-md">person</i>
                    <span>My profile</span>
                    </a>

                    <form method="post" action="{% url 'logout' %}">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-sm bg-gradient-primary mb-0 me-1 mt-2 mt-md-0 border-radius-md">
                        Logout
                      </button>
                    </form>
                  {% else %}
                    <a href="{% url 'login' %}" class="nav-link d-flex align-items-center text-md ps-2">
                    <i class="material-icons opacity-6 me-2 text-md">person</i>
                    <span>My profile</span>
                  </a>

                    <a href="{% url 'login' %}" class="btn btn-sm bg-gradient-primary mb-0 me-1 mt-2 mt-md-0 border-radius-md">
                      <span>Login</span>
                    </a>
                  {% endif %}
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% if page_obj.has_other_pages %}
<div class="row text-center py-2">
  <div class="col-4 mx-auto">
    <ul class="pagination pagination-primary" style="justify-content: center">

      <!-- Button prev" -->
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page= {{ page_obj.previous_page_number }}">
            <span aria-hidden="true">
              <i class="material-icons opacity-6 text-lg">arrow_back</i>
            </span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled"><span class="page-link"><i class="material-icons opacity-6 text-lg">arrow_back</i></span></li>
      {% endif %}

      <!-- Page numbers -->
      {% for i in page_obj.paginator.page_range %}
        {% if i >= page_obj.number|add:"-2" and i <= page_obj.number|add:"2" %}
          <li class="page-item {% if page_obj.number == i %}active{% endif %}">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}

      <!-- Button next -->
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page= {{ page_obj.next_page_number }}" aria-label="Last">
            <span aria-hidden="true">
              <i class="material-icons opacity-6 text-lg">arrow_forward</i>
            </span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled"><span class="page-link"><i class="material-icons opacity-6 text-lg">arrow_forward</i></span></li>
      {% endif %}
    </ul>
  </div>
</div>
{% endif %}

templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="{{ ASSETS_ROOT }}/assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
<script src="{{ ASSETS_ROOT }}/assets/js/plugins/perfect-scrollbar.min.js"></script>

<!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
<script src="{{ ASSETS_ROOT }}/assets/js/plugins/countup.min.js"></script>
<script src="{{ ASSETS_ROOT }}/assets/js/plugins/choices.min.js"></script>
<script src="{{ ASSETS_ROOT }}/assets/js/plugins/prism.min.js"></script>
<script src="{{ ASSETS_ROOT }}/assets/js/plugins/highlight.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
<script src="{{ ASSETS_ROOT }}/assets/js/plugins/rellax.min.js"></script>
<!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
<script src="{{ ASSETS_ROOT }}/assets/js/plugins/tilt.min.js"></script>
<!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
<script src="{{ ASSETS_ROOT }}/assets/js/plugins/choices.min.js"></script>

<!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
<script src="{{ ASSETS_ROOT }}/assets/js/plugins/parallax.min.js"></script>

<!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
<script src="{{ ASSETS_ROOT }}/assets/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>

templates/includes/sidebar.html
<ul class="sidebar-nav">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
  {% endif %}

  <br>
  <li><a href="{% url "publication:index" %}">Home page</a></li>
  <li><a href="{% url "publication:topic-list" %}">Topics</a></li>
  <li><a href="{% url "publication:newspaper-list" %}">Newspapers</a></li>
  <li><a href="{% url "publication:redactor-list" %}">Redactors</a></li>
</ul>